services:
  api-gateway:
    build:
      context: ../api_gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "300:80"
    environment:
      OTEL_SERVICE_NAME: api-gateway
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317 

    networks:
      sesc_infra_net:
        aliases:
          - api-gateway
      sesc_app_net:
        aliases:
          - api-gateway
  student-service:
    build:
      context: ../student_service
      dockerfile: Dockerfile
    container_name: student-service
    environment:
      OTEL_SERVICE_NAME: student-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317 
    env_file:
      - .student.app.env
    ports:
      - "8090:8080"
    networks:
      sesc_infra_net:
        aliases:
          - student-service
      sesc_app_net:

  finance-service:
    build:
      context: ../finance_service
      dockerfile: Dockerfile
    environment:
      OTEL_SERVICE_NAME: finance-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317 
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    env_file:
      - .finance.app.env
    ports:
      - "8081:8080"
    networks:
      sesc_infra_net:
        aliases:
          - finance-service
      sesc_app_net:

  library-service:
    build:
      context: ../library_service
      dockerfile: Dockerfile
    container_name: library-service
    env_file:
      - .library.app.env
    volumes:
      - ../library_service/migrations/mysql-migrations.sql:/docker-entrypoint-initdb.d/mysql-migrations.sql
    ports:
      - "8082:80"
    networks:
      sesc_infra_net:
        aliases:
          - library-service
      sesc_app_net:
networks:
  sesc_infra_net:
    external: true
  observability:
    external: true
  sesc_app_net:
    driver: bridge