# docker-compose.obs.yml
services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./observability/otel/collector-config.yaml:/etc/otel-collector-config.yaml:ro
      # host-metrics scrapers:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "8889:8889" # Prometheus receiver
    networks:
      sesc_infra_net:
        aliases:
          - otel-collector
      observability:
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - sesc_infra_net
      - observability

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./observability/loki/loki-config.yml:/etc/loki/config.yml
      - loki_data:/loki
      - ./observability/loki/wal:/wal
      - ./observability/loki/storage:/loki
    networks:
      - observability

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: -config.file=/etc/tempo/tempo.yml
    volumes:
      - ./observability/tempo/tempo.yml:/etc/tempo/tempo.yml:ro
    ports:
      - "3200:3200"
    networks:
      - observability

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - ./observability/grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - otel-collector
      - loki
      - tempo
    networks:
      - observability

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./observability/promtail/config.yml:/etc/promtail/config.yml:ro
    networks:
      - observability


volumes:
  prometheus_data: {}
  grafana_data: {}
  loki_data: {}

networks:
  sesc_infra_net:
    external: true
  observability:
    external: true
