server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:


metrics_generator:
  processor:
    span_metrics:
      dimensions:
        - service.name
        - span.kind
        - http.method
        - http.status_code

ingester:
  trace_idle_period: 10s
  max_block_bytes: 5_000_000
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 1h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces
