server:
  port: 80

spring:
  application:
    name: api-gateway

  cloud:
    compatibility-verifier:
      compatible-boot-versions: 3.4.5
    consul:
      host: consul
      port: 8500
    discovery:
      service-name: ${spring.application.name}
      health-check-path: /actuator/health
      health-check-interval: 10s
      deregister-critical-service-after: 30s
      prefer-ip-address: false
      locator:
        enabled: true
        lower-case-service-id: true

    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        - id: student
          uri: lb://student-service
          predicates:
            - Path=/student/**
          filters:
            - StripPrefix=1   
        # - id: student
        #   uri: lb://student-service
        #   predicates:
        #     - "Host=students.local"
        #     - "Path=/**"
        - id: finance
          uri: lb://finance-service
          predicates:
            - Path=/finance/**
          filters:
            - StripPrefix=1   
        # - id: finance
        #   uri: lb://finance-service
        #   predicates:
        #     - "Host=finance.local"
        #     - "Path=/**"
        - id: library
          uri: lb://library-service
          predicates:
            - Path=/library/**
          filters:
            - StripPrefix=1   
        # - id: library
        #   uri: lb://library-service
        #   predicates:
        #     - "Host=library.local"
        #     - "Path=/**"


management:
  endpoints:
    web:
      exposure:
        include: health
